version: "3.9"

services:
  client:
    container_name: react-client
    build:
      context: .
    volumes:
      - ./node_modules/@rcpch/digital-growth-charts-react-component-library:/Users/SimonChapman/Development/RCPCHProjects/digital-growth-charts-react-component-library
    ports:
      - "3000:3000"